apiVersion: v1
kind: Service #, Pod, Deployment, Ingresse, .... type 
metadata: 
  name: dev-srv
spec:
  type: NodePort
  selector:
    app: dev #respect dans le client pod metadata labels
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31007