apiVersion: v1
kind: Service #, Pod, Deployment, Ingresse, .... type 
metadata: 
  name: test-srv
spec:
  type: NodePort
  selector:
    app: test #respect dans le client pod metadata labels
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 33007