apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-dpl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: dev
  template:  # template fabric pod
    metadata:
      name: dev-pod
      labels:
        app: dev #nomination au choix ==> jsghsdj: serghsef
    spec: 
      containers:
        - name: dev  #docker --name
          image: omarnbr/tpcicd:v1 #docker tag



---
apiVersion: v1
kind: Service #, Pod, Deployment, Ingresse, .... type 
metadata: 
  name: dev-srv
spec:
  type: NodePort
  selector:
    app: dev #respect dans le client pod metadata labels
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30012