apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-dpl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: prod
  template:  
    metadata:
      name: prod-pod
      labels:
        app: prod 
    spec: 
      containers:
        - name: prod  #docker --name
          image: medomartp/tpcicd #docker tag



---
apiVersion: v1
kind: Service  
metadata: 
  name: prod-srv
spec:
  type: NodePort
  selector:
    app: prod #respect dans le client pod metadata labels
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30010