apiVersion: v1
kind: Pod #Service, Deployment, Ingresse, .... type 
metadata:
  name: dev-pod
  labels:
    app: dev #nomination au choix ==> jsghsdj: serghsef
spec: 
  containers:
    - name: dev  #docker --name
      image: omarnbr/tpcicd:v1 #docker tag