apiVersion: v1
kind: Pod #Service, Deployment, Ingresse, .... type 
metadata:
  name: prod-pod
  labels:
    app: prod #nomination au choix ==> jsghsdj: serghsef
spec: 
  containers:
    - name: prod  #docker --name
      image: medomartp/tpcicd #docker tag